(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const canvas=$('#game'),ctx=canvas.getContext('2d',{alpha:false});
let W=0,H=0,DPR=1,uiScale=1,registry,data,levelsData,levelsPromise,physicsData,atlasImages=new Map(),screen='loading',time=0,last=performance.now();
const TILE_W=196,TILE_H=97,MAP_ORIGIN_X=70*TILE_W/2;
const camera={x:5480,y:2380,zoom:1,drag:false,startX:0,startY:0,baseX:0,baseY:0,moved:false};
const pointers=new Map();
const audio={title:new Audio('assets/audio/title_theme.mp3'),ambient:new Audio('assets/audio/hatchery_ambient.mp3')};
audio.title.loop=audio.ambient.loop=true;audio.title.volume=.38;audio.ambient.volume=.34;
let soundOn=true,titleButton={x:0,y:0,w:0,h:0},placement=null,selected=null,toastTimer=0,slingshot=null;
let baseTiles=[],worldDecor=[],worldObstacles=[],dynamicDecor=[];

const freshSave=()=>({version:2,stars:60,coins:300,objects:[
 {id:'nest-1',type:'nest',x:5480,y:2400,state:'empty',created:Date.now()}
],removed:[],taskTier:0,taskProgress:[0,0,0],scores:{},sound:true});
let save=loadSave();soundOn=save.sound!==false;
function loadSave(){try{const parsed=JSON.parse(localStorage.getItem('hatchery-island-save')||'{}'),merged={...freshSave(),...parsed};if(!parsed.version||parsed.version<2){merged.objects=(merged.objects||[]).filter(o=>o.id!=='bird-1'&&o.id!=='bird-2');merged.version=2;localStorage.setItem('hatchery-island-save',JSON.stringify(merged))}return merged}catch{return freshSave()}}
function persist(){localStorage.setItem('hatchery-island-save',JSON.stringify(save))}
function play(name,vol=.7){if(!soundOn)return;const a=new Audio(`assets/audio/${name}`);a.volume=vol;a.play().catch(()=>{})}
function setMusic(which){Object.values(audio).forEach(a=>{if(a!==audio[which]){a.pause();a.currentTime=0}});if(soundOn&&which)audio[which].play().catch(()=>{})}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1500)}

class SpriteLibrary{
 constructor(reg){this.reg=reg}
 async load(){const jobs=Object.entries(this.reg.atlases).map(([name,url])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{atlasImages.set(name,im);resolve()};im.onerror=reject;im.src=url}));await Promise.all(jobs)}
 meta(name){return this.reg.sprites[name]}
 draw(name,x,y,scale=1,angle=0,alpha=1,context=ctx){const s=this.meta(name);if(!s)return false;const im=atlasImages.get(s.atlas);if(!im)return false;context.save();context.globalAlpha=alpha;context.translate(x,y);context.rotate(angle);context.scale(scale,scale);context.drawImage(im,s.x,s.y,s.w,s.h,-s.ox,-s.oy,s.w,s.h);context.restore();return true}
 drawCentered(name,x,y,maxW,maxH,context=ctx){const s=this.meta(name);if(!s)return;const scale=Math.min(maxW/s.w,maxH/s.h);const im=atlasImages.get(s.atlas);context.drawImage(im,s.x,s.y,s.w,s.h,x-s.w*scale/2,y-s.h*scale/2,s.w*scale,s.h*scale)}
 raw(name){const s=this.meta(name);return s&&{s,image:atlasImages.get(s.atlas)}}
}
let sprites;

function resize(){const r=canvas.getBoundingClientRect();DPR=Math.min(1.5,devicePixelRatio||1);W=r.width;H=r.height;canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);uiScale=Math.min(W/1024,H/768)}
addEventListener('resize',resize);resize();

async function boot(){
 try{
  levelsPromise=fetch('assets/data/levels.json').then(r=>r.json()).then(v=>(levelsData=v));const [s,g,p]=await Promise.all([fetch('assets/data/sprites.json').then(r=>r.json()),fetch('assets/data/game-data.json').then(r=>r.json()),fetch('assets/data/physics.json').then(r=>r.json())]);registry=s;data=g;physicsData=p;sprites=new SpriteLibrary(s);await sprites.load();prepareMap();$('#loading').hidden=true;screen='title';requestAnimationFrame(frame)
 }catch(e){$('#loading b').textContent='LOAD ERROR: '+e.message;console.error(e)}
}
function tilePoint(col,row){return{x:(col-row)*TILE_W/2+MAP_ORIGIN_X,y:(col+row)*TILE_H/2}}
function prepareMap(){
 const layers=Object.fromEntries(data.map.layers.map(l=>[l.name,l]));const defs=data.objects;
 for(let row=0;row<70;row++)for(let col=0;col<70;col++){
  const i=row*70+col,p=tilePoint(col,row),base=layers.Base.data[i],dyn=layers.Dynamic.data[i];
  if(base&&defs[String(base)]?.sprites?.[0])baseTiles.push({x:p.x,y:p.y,sprite:defs[String(base)].sprites[0]});
  if(dyn&&defs[String(dyn)]?.sprites?.[0])worldObstacles.push({id:`map-${i}`,gid:dyn,x:p.x,y:p.y,sprite:defs[String(dyn)].sprites[0],def:defs[String(dyn)]});
 }
 const make=(o,i)=>{const def=defs[String(o.gid)];return def?.sprites?.[0]?{id:`deco-${i}`,gid:o.gid,x:o.x,y:o.y,sprite:def.sprites[0],def}:null};
 worldDecor=layers.Decoration.objects.map(make).filter(Boolean);dynamicDecor=layers.DynamicDecoration.objects.map(make).filter(Boolean);
 worldObstacles=worldObstacles.filter(o=>!save.removed.includes(o.id));updateHud()
}

function visible(x,y,pad=220){const l=camera.x-W/(2*camera.zoom)-pad,r=camera.x+W/(2*camera.zoom)+pad,t=camera.y-H/(2*camera.zoom)-pad,b=camera.y+H/(2*camera.zoom)+pad;return x>l&&x<r&&y>t&&y<b}
function worldTransform(){ctx.translate(W/2-camera.x*camera.zoom,H/2-camera.y*camera.zoom);ctx.scale(camera.zoom,camera.zoom)}
function renderTitle(){
 ctx.fillStyle='#12a6bd';ctx.fillRect(0,0,W,H);const bg=sprites.raw('MENU_BACKGROUND_TOP');if(bg){ctx.drawImage(bg.image,bg.s.x,bg.s.y,bg.s.w,bg.s.h,0,0,W/2,H);ctx.save();ctx.translate(W,0);ctx.scale(-1,1);ctx.drawImage(bg.image,bg.s.x,bg.s.y,bg.s.w,bg.s.h,0,0,W/2,H);ctx.restore()}
 sprites.drawCentered('MENU_LOGO',W/2,H*.22,W*.82,H*.3);const pulse=1+Math.sin(time*3)*.025;const m=sprites.meta('H_BUTTON_HATCHERY'),bw=Math.min(W*.34,390)*pulse,bh=bw*(m.h/m.w);sprites.drawCentered('H_BUTTON_HATCHERY',W/2,H*.59,bw,bh);titleButton={x:W/2-bw/2,y:H*.59-bh/2,w:bw,h:bh};
 drawBird(data.prototypeBirds[0],W*.25,H*.73,uiScale*.85,0);drawBird(data.prototypeBirds[2],W*.75,H*.73,uiScale*.85,0);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font=`900 ${Math.max(15,23*uiScale)}px Arial Rounded MT Bold`;ctx.shadowColor='#07516b';ctx.shadowBlur=4;ctx.fillText('TAP HATCHERY TO ENTER',W/2,H*.9);ctx.shadowBlur=0
}

function renderWorld(){
 ctx.fillStyle='#71cddd';ctx.fillRect(0,0,W,H);ctx.save();worldTransform();
 for(const t of baseTiles)if(visible(t.x,t.y,150))sprites.draw(t.sprite,t.x,t.y);
 const drawables=[];
 for(const o of worldDecor)if(visible(o.x,o.y))drawables.push(o);
 for(const o of dynamicDecor)if(visible(o.x,o.y))drawables.push(o);
 for(const o of worldObstacles)if(visible(o.x,o.y))drawables.push(o);
 for(const o of save.objects)if(visible(o.x,o.y,260))drawables.push(o);
 drawables.sort((a,b)=>(a.y+(a.def?.renderQueue||0)*2)-(b.y+(b.def?.renderQueue||0)*2));
 for(const o of drawables)drawWorldObject(o);
 if(placement){const p=screenToWorld(placement.pointerX,placement.pointerY),tile=worldToTile(p.x,p.y),snap=tilePoint(tile.col,tile.row);ctx.globalAlpha=.65;drawPlacement(placement.type,snap.x,snap.y);ctx.globalAlpha=1}
 ctx.restore();
}
function getBird(o){return o.custom||data.prototypeBirds[o.birdIndex%data.prototypeBirds.length]}
function drawWorldObject(o){
 if(o.type==='nest'){const bob=Math.sin(time*2+o.x)*1.5;sprites.draw('H_GAME_OBJECT_NEST_1_BOTTOM',o.x,o.y+bob);if(o.state==='incubating'||o.state==='ready')sprites.draw('H_GAME_OBJECT_EGG_1',o.x,o.y-48+bob,.52,Math.sin(time*4)*.03);sprites.draw('H_GAME_OBJECT_NEST_1_TOP',o.x,o.y+bob);if(o.state==='incubating')drawTimer(o)}
 else if(o.type==='bird'){const b=getBird(o);drawBird(b,o.x,o.y+Math.sin(time*2.1+o.birdIndex)*5,.5,time)}
 else{let angle=0,scale=1;if(o.def?.animation){angle=Math.sin(time*(o.def.animation.speedMin||1)+o.x)*.025;scale=1+Math.sin(time*1.7+o.y)*.012}sprites.draw(o.sprite,o.x,o.y,scale,angle)}
}
function drawPlacement(type,x,y){if(type==='nest'||(type==='move'&&placement.object?.type==='nest')){sprites.draw('H_GAME_OBJECT_NEST_1_BOTTOM',x,y);sprites.draw('H_GAME_OBJECT_NEST_1_TOP',x,y)}else if(type==='move'&&placement.object?.type==='bird'){drawBird(getBird(placement.object),x,y,.5,time)}else sprites.draw('H_GAME_OBJECT_EGG_1',x,y-40,.5)}
function drawTimer(o){const elapsed=(Date.now()-o.created)/1000,ratio=clamp(elapsed/60,0,1);if(ratio>=1)o.state='ready';ctx.save();ctx.translate(o.x-42,o.y-105);ctx.fillStyle='#123b48cc';ctx.fillRect(0,0,84,9);ctx.fillStyle='#ffcc1b';ctx.fillRect(2,2,80*ratio,5);ctx.restore()}
function drawBird(b,x,y,scale=.5,t=time,context=ctx){if(!b)return;const shape=b.shape||'RED',color=b.color||shape,eyes=b.eyes||shape,beak=b.beak||shape;let body=b.sprite||`BIRD_BODY_${shape}_${color}`;if(!sprites.meta(body))body='BIRD_BODY_RED_RED';const blink=(t+Number(b.id||0))%4<.12,eyeNormal=`BIRD_EYES_${eyes}_NORMAL`,eyeBlink=`BIRD_EYES_${eyes}_BLINK`,mouth=`BIRD_BEAK_${beak}_NORMAL`;context.save();context.translate(x,y+Math.sin(t*2+Number(b.id||0))*2);const parts=b.sprites||[];if(parts.length){for(const part of parts){let name=part.sprite;if(String(name).startsWith('BIRD_BODY_'))name=body;else if(String(name).startsWith('BIRD_EYES_'))name=blink&&sprites.meta(eyeBlink)?eyeBlink:eyeNormal;else if(String(name).startsWith('BIRD_BEAK_'))name=mouth;if(!sprites.meta(name))continue;sprites.draw(name,(part.x||0)*scale,(part.y||0)*scale,scale*(part.scale||1),-(part.angle||0),1,context)}}else{sprites.draw(body,0,0,scale,0,1,context);sprites.draw(blink&&sprites.meta(eyeBlink)?eyeBlink:eyeNormal,4*scale,-18*scale,scale,0,1,context);sprites.draw(mouth,28*scale,7*scale,scale,0,1,context)}context.restore()}

function screenToWorld(x,y){return{x:(x-W/2)/camera.zoom+camera.x,y:(y-H/2)/camera.zoom+camera.y}}
function worldToTile(x,y){const dx=x-MAP_ORIGIN_X,a=dx/(TILE_W/2),b=y/(TILE_H/2);return{col:clamp(Math.round((a+b)/2),0,69),row:clamp(Math.round((b-a)/2),0,69)}}
function objectAt(x,y){const all=[...save.objects,...worldObstacles];let best=null,dist=95/camera.zoom;for(const o of all){const d=Math.hypot(o.x-x,o.y-y);if(d<dist){best=o;dist=d}}return best}

function handleTap(x,y){
 if(screen==='title'){if(x>=titleButton.x&&x<=titleButton.x+titleButton.w&&y>=titleButton.y&&y<=titleButton.y+titleButton.h){play('menu_confirm.mp3');setMusic('ambient');screen='world';$('#hud').hidden=false;toast('WELCOME TO HATCHERY ISLAND!')}return}
 if(screen!=='world')return;const w=screenToWorld(x,y);
 if(placement){const tile=worldToTile(w.x,w.y),p=tilePoint(tile.col,tile.row);if(placement.type==='nest'){if(save.coins<20)return toast('NOT ENOUGH COINS');save.coins-=20;save.objects.push({id:'nest-'+Date.now(),type:'nest',x:p.x,y:p.y,state:'empty',created:Date.now()});play('h_purchase.wav')}else if(placement.type==='move'&&placement.object){placement.object.x=p.x;placement.object.y=p.y;play('abi_inventory_place.mp3')}placement=null;$$('.tools button').forEach(b=>b.classList.remove('active'));persist();updateHud();return}
 const o=objectAt(w.x,w.y);if(o)openContext(o)
}
function openContext(o){selected=o;const box=$('#contextMenu'),title=$('#contextTitle'),text=$('#contextText'),actions=$('#contextActions');actions.innerHTML='';box.hidden=false;
 if(o.type==='nest'){title.textContent='NEST';if(o.state==='empty'){text.textContent='This nest is ready for an egg.';addAction('ADD EGG · 20',()=>addEgg(o))}else if(o.state==='incubating'){const left=Math.max(0,Math.ceil(60-(Date.now()-o.created)/1000));text.textContent=`The egg hatches in ${left} seconds.`;addAction('HURRY · 10 ★',()=>hurry(o))}else{text.textContent='The egg is ready to hatch!';addAction('HATCH!',()=>hatch(o))}addAction('MOVE',()=>beginMove(o))}
 else if(o.type==='bird'){title.textContent='HATCHED BIRD';text.textContent='View or customize this bird.';addAction('CUSTOMIZE',()=>openBirdDesigner(o));addAction('REMOVE',()=>removeUser(o))}
 else{title.textContent='CLEAR OBSTACLE';text.textContent='Clear this object to make room for a nest.';addAction('CLEAR · 20',()=>clearObstacle(o))}}
function addAction(label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{play('menu_confirm.mp3');$('#contextMenu').hidden=true;fn()};$('#contextActions').append(b)}
function addEgg(n){if(save.coins<20)return toast('NOT ENOUGH COINS');save.coins-=20;n.state='incubating';n.created=Date.now();persist();updateHud();play('h_egg_selected.wav');toast('EGG ADDED')}
function hurry(n){if(save.stars<10)return toast('NOT ENOUGH STARS');save.stars-=10;n.state='ready';persist();updateHud();play('h_marker_1.mp3')}
function hatch(n){const index=Math.floor(Math.random()*data.prototypeBirds.length),id='bird-'+Date.now();save.objects.push({id,type:'bird',x:n.x+95,y:n.y+25,birdIndex:index});n.state='empty';n.created=Date.now();progressTask(data.prototypeBirds[index]);persist();play('h_bird_hatched_popup.mp3');toast('A NEW BIRD HATCHED!')}
function beginMove(o){placement={type:'move',object:o,pointerX:W/2,pointerY:H/2};toast('TAP A NEW LOCATION')}
function removeUser(o){save.objects=save.objects.filter(x=>x.id!==o.id);persist()}
function clearObstacle(o){if(save.coins<20)return toast('NOT ENOUGH COINS');save.coins-=20;worldObstacles=worldObstacles.filter(x=>x.id!==o.id);save.removed.push(o.id);persist();updateHud();play('abi_remove_item.mp3');toast('AREA CLEARED')}

async function showLevels(initialPack='pack1'){const birds=save.objects.filter(o=>o.type==='bird');$('#panelTitle').textContent='CHOOSE A LEVEL';const body=$('#panelBody');if(!levelsData){body.innerHTML='<p>Loading all 325 original levels…</p>';openPanel();await levelsPromise;}if(!birds.length){body.innerHTML='<p><b>Hatch at least one bird first.</b> Your custom Hatchery birds become the slingshot team.</p>';return openPanel()}const packs=[...new Set(levelsData.levels.map(l=>l.pack))].sort((a,b)=>(parseInt(a.match(/\d+/)?.[0])||999)-(parseInt(b.match(/\d+/)?.[0])||999));body.innerHTML='<select id="packSelect"></select><div class="level-grid"></div>';const select=$('#packSelect',body);for(const pack of packs){const o=document.createElement('option');o.value=pack;o.textContent=pack==='goldeneggs1'?'GOLDEN EGGS':pack.toUpperCase().replace('PACK','EPISODE ');select.append(o)}select.value=packs.includes(initialPack)?initialPack:packs[0];const render=()=>{const levels=levelsData.levels.filter(l=>l.pack===select.value).sort((a,b)=>(parseInt(a.id.match(/\d+/)?.[0])||0)-(parseInt(b.id.match(/\d+/)?.[0])||0)),grid=$('.level-grid',body);grid.innerHTML='';levels.forEach((level,i)=>{const b=document.createElement('button');b.className='level-button';b.innerHTML=`<strong>${i+1}</strong><span>${'★'.repeat(save.scores[`${level.pack}/${level.id}`]||0)}${'☆'.repeat(3-(save.scores[`${level.pack}/${level.id}`]||0))}</span>`;b.onclick=()=>startLevel(level,i+1);grid.append(b)})};select.onchange=render;render();openPanel()}

function startLevel(level,number){const roster=save.objects.filter(o=>o.type==='bird').slice(0,5);if(!roster.length)return toast('HATCH A BIRD FIRST');closePanel();$('#hud').hidden=true;screen='slingshot';setMusic(null);play('level start military a1.mp3');const M=window.Matter,engine=M.Engine.create({gravity:{x:0,y:1,scale:.001}}),world=engine.world;const groundY=H*.79,originX=W*.1,unit=Math.min(W/72,H/48);slingshot={level,number,engine,world,bodies:[],roster,queueIndex:0,current:null,sling:{x:originX+3*unit,y:groundY-4.5*unit},groundY,originX,unit,dragging:false,launchedAt:0,special:false,score:0,complete:false,failed:false};M.World.add(world,M.Bodies.rectangle(W/2,groundY+28,W*2,60,{isStatic:true,friction:1,label:'ground'}));
 const entries=Object.values(level.world);for(const o of entries){const def=physicsData.blocks?.[o.definition];if(!def||/Bird$/.test(o.definition)||o.definition==='Ground'||o.definition==='ShootingPlatform01')continue;const meta=sprites.meta(def.sprite);if(!meta)continue;const x=originX+(o.x+15)*unit,y=groundY+o.y*unit,mat=physicsData.materials?.[def.material]||{},isPig=/Piglette/.test(o.definition),isStatic=def.density===0||['immovable','staticGround','decoration'].includes(def.material)||String(o.definition).startsWith('Static');let body;if(isPig||def.type==='circle')body=M.Bodies.circle(x,y,Math.max(8,(meta.w+meta.h)/4),{isStatic,restitution:def.restitution??mat.restitution??.1,friction:def.friction??mat.friction??.7,density:def.density??mat.density??1});else body=M.Bodies.rectangle(x,y,Math.max(5,meta.w),Math.max(5,meta.h),{isStatic,restitution:def.restitution??mat.restitution??.1,friction:def.friction??mat.friction??.7,density:def.density??mat.density??1,angle:-(o.angle||0)});body.label=isPig?'pig':'block';body.plugin.render={sprite:def.sprite,definition:o.definition};body.plugin.health=(def.strength??mat.strength??40)*(isPig?5:2);slingshot.bodies.push(body);M.World.add(world,body)}
 M.Events.on(engine,'collisionStart',event=>{for(const pair of event.pairs){const speed=Math.max(pair.bodyA.speed,pair.bodyB.speed),hit=body=>{if(!['pig','block'].includes(body.label)||speed<2)return;body.plugin.health-=speed*8;if(body.plugin.health<=0){slingshot.score+=body.label==='pig'?5000:500;play(body.label==='pig'?'piglette destroyed.mp3':'wood destroyed a1.mp3',.55);M.World.remove(world,body)}};hit(pair.bodyA);hit(pair.bodyB)}});loadNextBird()}
function loadNextBird(){const S=slingshot,M=Matter;if(!S||S.queueIndex>=S.roster.length){if(!S.current)S.failed=true;return}const source=S.roster[S.queueIndex++],body=M.Bodies.circle(S.sling.x,S.sling.y,22,{isStatic:true,restitution:.35,friction:.5,density:1});body.label='playerBird';body.plugin.source=source;M.World.add(S.world,body);S.current=body;S.dragging=false;S.special=false;S.launchedAt=0}
function launchBird(x,y){const S=slingshot,M=Matter;if(!S?.current||!S.current.isStatic)return;const dx=clamp(x-S.sling.x,-115,55),dy=clamp(y-S.sling.y,-95,95);M.Body.setPosition(S.current,{x:S.sling.x+dx,y:S.sling.y+dy});M.Body.setStatic(S.current,false);M.Body.setVelocity(S.current,{x:-dx*.18,y:-dy*.18});S.dragging=false;S.launchedAt=performance.now();play('bird shot-a1.mp3',.7)}
function activateSpecial(){const S=slingshot,M=Matter,b=S?.current;if(!b||b.isStatic||S.special)return;S.special=true;const bird=getBird(b.plugin.source),shape=bird.shape||'RED';if(shape==='YELLOW'){M.Body.setVelocity(b,{x:b.velocity.x*1.7,y:b.velocity.y*1.7});play('h_specialty_boost.mp3')}else if(shape==='BLACK'){for(const x of M.Composite.allBodies(S.world)){const d=Math.hypot(x.position.x-b.position.x,x.position.y-b.position.y);if(d<145&&!x.isStatic)M.Body.applyForce(x,x.position,{x:(x.position.x-b.position.x)*.0007,y:(x.position.y-b.position.y)*.0007})}play('h_specialty_explosion.mp3')}else if(shape==='BLUE'){for(const a of [-.28,.28]){const q=M.Bodies.circle(b.position.x,b.position.y,14,{restitution:.35});q.label='playerBird';q.plugin.source=b.plugin.source;M.Body.setVelocity(q,{x:b.velocity.x*Math.cos(a)-b.velocity.y*Math.sin(a),y:b.velocity.x*Math.sin(a)+b.velocity.y*Math.cos(a)});M.World.add(S.world,q);S.bodies.push(q)}play('bird 02 flying.mp3')}else if(shape==='GREEN'){M.Body.setVelocity(b,{x:-Math.abs(b.velocity.x)*1.25,y:b.velocity.y-2});play('boomerang_activate.mp3')}else if(shape==='WHITE'){const egg=M.Bodies.circle(b.position.x,b.position.y+20,13,{density:2,restitution:.15});egg.label='playerBird';egg.plugin.source=b.plugin.source;M.Body.setVelocity(egg,{x:b.velocity.x*.5,y:7});M.World.add(S.world,egg);S.bodies.push(egg);M.Body.setVelocity(b,{x:b.velocity.x,y:b.velocity.y-8});play('bird pushing egg out.mp3')}else play('bird misc a1.mp3')}
function updateSlingshot(dt){const S=slingshot;if(!S)return;Matter.Engine.update(S.engine,dt*1000);S.bodies=S.bodies.filter(b=>Matter.Composite.allBodies(S.world).includes(b));const pigs=Matter.Composite.allBodies(S.world).filter(b=>b.label==='pig');if(!pigs.length&&!S.complete){S.complete=true;const stars=clamp(Math.ceil((S.score+S.roster.length*1000)/7000),1,3);save.scores[`${S.level.pack}/${S.level.id}`]=Math.max(save.scores[`${S.level.pack}/${S.level.id}`]||0,stars);persist();setTimeout(()=>showLevelResult(true,stars),900)}const b=S.current;if(b&&!b.isStatic&&S.launchedAt){const age=(performance.now()-S.launchedAt)/1000;if(age>7||(age>1.4&&b.speed<.35)||b.position.y>H+300){Matter.World.remove(S.world,b);S.current=null;if(!S.complete)setTimeout(loadNextBird,600)}}if(S.failed&&!S.complete)showLevelResult(false,0)}
function renderSlingshot(){const S=slingshot;ctx.fillStyle='#8ed9f4';ctx.fillRect(0,0,W,H);const bg=sprites.raw('BACKGROUND_1_LAYER_2');if(bg){for(let x=0;x<W;x+=bg.s.w)ctx.drawImage(bg.image,bg.s.x,bg.s.y,bg.s.w,bg.s.h,x,H-bg.s.h,bg.s.w,bg.s.h)}ctx.fillStyle='#6eac3b';ctx.fillRect(0,S.groundY,W,H-S.groundY);sprites.draw('SLING_SHOT_01_BACK',S.sling.x,S.sling.y+30,1,0,1,ctx);
 for(const body of Matter.Composite.allBodies(S.world)){if(['ground'].includes(body.label))continue;ctx.save();ctx.translate(body.position.x,body.position.y);ctx.rotate(body.angle);if(body.label==='playerBird')drawBird(getBird(body.plugin.source),0,0,.33,time,ctx);else{const n=body.plugin.render?.sprite;if(n)sprites.draw(n,0,0,1,0,1,ctx)}ctx.restore()}sprites.draw('SLING_SHOT_01_FRONT',S.sling.x,S.sling.y+30,1,0,1,ctx);
 if(S.current?.isStatic){ctx.strokeStyle='#fff8';ctx.lineWidth=3;ctx.setLineDash([6,8]);ctx.beginPath();ctx.moveTo(S.sling.x,S.sling.y);ctx.lineTo(S.sling.x+150,S.sling.y-70);ctx.stroke();ctx.setLineDash([])}ctx.fillStyle='#fff';ctx.strokeStyle='#173845';ctx.lineWidth=5;ctx.font='900 26px Arial';ctx.strokeText(`LEVEL ${S.number}   SCORE ${S.score}`,90,45);ctx.fillText(`LEVEL ${S.number}   SCORE ${S.score}`,90,45);ctx.beginPath();ctx.arc(42,42,29,0,Math.PI*2);ctx.fillStyle='#078da9';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle='#fff';ctx.font='900 26px Arial';ctx.fillText('‹',34,50)}
function showLevelResult(win,stars){if($('#panel').hidden===false)return;$('#panelTitle').textContent=win?'LEVEL COMPLETE!':'TRY AGAIN';$('#panelBody').innerHTML=`<div style="text-align:center;font-size:2rem;color:#f4a000">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p style="text-align:center">Score: ${slingshot.score}</p><div style="text-align:center"><button class="action" id="retryLevel">RETRY</button><button class="action" id="backIsland">HATCHERY</button></div>`;openPanel();$('#retryLevel').onclick=()=>startLevel(slingshot.level,slingshot.number);$('#backIsland').onclick=exitLevel;play(win?'level_complete.mp3':'level failed piglets a1.mp3')}
function exitLevel(){closePanel();slingshot=null;screen='world';$('#hud').hidden=false;setMusic('ambient')}
function updateHud(){$('#stars').textContent=save.stars;$('#coins').textContent=save.coins;$('#soundButton').textContent=soundOn?'♫':'×'}

function progressTask(bird){const tier=data.tasks[save.taskTier];if(!tier)return;tier.tasks.forEach((t,i)=>{if(t.taskType==='HATCH_ANY_KIND_OF_BIRD')save.taskProgress[i]++;else if(t.taskType==='HATCH_BIRD_OF_COLOR'&&(bird.shape===t.identifier||bird.color===t.identifier))save.taskProgress[i]++;else if(t.taskType==='HATCH_BIRD_OF_GENDER')save.taskProgress[i]++;else if(t.taskType==='HATCH_BIRD_WITH_ACCESSORY'&&(bird.sprites||[]).some(s=>String(s.sprite).includes('ACCESSORY')))save.taskProgress[i]++});save.taskProgress=save.taskProgress.map((v,i)=>Math.min(v,tier.tasks[i].amount))}

function showBirds(){const body=$('#panelBody');$('#panelTitle').textContent='MY BIRDS';body.innerHTML='<div class="bird-grid"></div>';const grid=$('.bird-grid',body);const birds=save.objects.filter(o=>o.type==='bird');if(!birds.length)body.innerHTML='<p>Hatch an egg to add your first bird.</p>';for(const o of birds){const card=document.createElement('button');card.className='bird-card';card.innerHTML='<canvas width="180" height="180"></canvas><b>BIRD '+(o.birdIndex+1)+'</b>';card.onclick=()=>openBirdDesigner(o);grid.append(card);const c=$('canvas',card),cctx=c.getContext('2d');drawBird(getBird(o),90,105,.72,time,cctx)}openPanel()}
function showTasks(){const tier=data.tasks[save.taskTier]||data.tasks.at(-1);$('#panelTitle').textContent='HATCHERY TASKS';const body=$('#panelBody');body.innerHTML='<div class="task-list"></div>';const list=$('.task-list',body);tier.tasks.forEach((t,i)=>{const done=(save.taskProgress[i]||0)>=t.amount,el=document.createElement('div');el.className='task-card '+(done?'done':'');el.innerHTML=`<b>${done?'✓':'○'} ${t.text}</b><p>${save.taskProgress[i]||0} / ${t.amount}</p>`;list.append(el)});if(tier.tasks.every((t,i)=>(save.taskProgress[i]||0)>=t.amount)){const b=document.createElement('button');b.className='action';b.textContent=`COLLECT ${tier.rewardAmount} ★`;b.onclick=()=>{save.stars+=tier.rewardAmount;save.taskTier=Math.min(save.taskTier+1,data.tasks.length-1);save.taskProgress=[0,0,0];persist();updateHud();showTasks();play('h_fanfare_1.wav')};body.append(b)}openPanel()}
function openBirdDesigner(o){selected=o;const bird=o.custom||(o.custom=JSON.parse(JSON.stringify(data.prototypeBirds[o.birdIndex])));$('#panelTitle').textContent='BIRD DESIGNER';const body=$('#panelBody');body.innerHTML='<canvas id="birdPreview" width="380" height="280" style="display:block;margin:auto;max-width:100%;background:radial-gradient(circle,#c8f5f4,#4cb5cb);border-radius:22px"></canvas><div style="text-align:center"><button class="action" data-cycle="body">BODY</button><button class="action" data-cycle="eyes">EYES</button><button class="action" data-cycle="beak">BEAK</button><button class="action" data-cycle="hat">HAT</button></div>';const redraw=()=>{const c=$('#birdPreview'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);drawBird(bird,190,165,1.1,time,x)};redraw();$$('[data-cycle]',body).forEach(btn=>btn.onclick=()=>{const types=data.birdDefinitions.DefaultIndexes,kind=btn.dataset.cycle;if(kind==='body'){bird.shape=types[(types.indexOf(bird.shape)+1)%types.length];bird.color=types[(types.indexOf(bird.color)+2)%types.length];bird.sprite=`BIRD_BODY_${bird.shape}_${bird.color}`;if(!sprites.meta(bird.sprite))bird.sprite='BIRD_BODY_RED_RED'}else if(kind==='eyes')bird.eyes=types[(types.indexOf(bird.eyes)+1)%types.length];else if(kind==='beak')bird.beak=types[(types.indexOf(bird.beak)+1)%types.length];else{bird.sprites=bird.sprites||[];bird.sprites.push({sprite:data.birdDefinitions.Sprites.AccessoryTop[Math.floor(Math.random()*data.birdDefinitions.Sprites.AccessoryTop.length)],x:0,y:-75,scale:.7,angle:0})}play('h_marker_2.mp3');redraw();persist()});openPanel()}
function openPanel(){$('#contextMenu').hidden=true;$('#panel').hidden=false}function closePanel(){$('#panel').hidden=true}

canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});camera.drag=true;camera.startX=e.clientX;camera.startY=e.clientY;camera.baseX=camera.x;camera.baseY=camera.y;camera.moved=false;if(!soundOn)return;if(screen==='title'&&audio.title.paused)setMusic('title')});
canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(placement){placement.pointerX=e.clientX;placement.pointerY=e.clientY;}if(pointers.size===1&&camera.drag&&screen==='world'){const dx=e.clientX-camera.startX,dy=e.clientY-camera.startY;if(Math.hypot(dx,dy)>5)camera.moved=true;camera.x=clamp(camera.baseX-dx/camera.zoom,100,13600);camera.y=clamp(camera.baseY-dy/camera.zoom,100,6700)}if(pointers.size===2&&screen==='world'){const ps=[...pointers.values()],d=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y);if(!camera.pinch){camera.pinch=d;camera.pinchZoom=camera.zoom}else camera.zoom=clamp(camera.pinchZoom*d/camera.pinch,.38,1.45)}});
canvas.addEventListener('pointerup',e=>{const wasMoved=camera.moved;pointers.delete(e.pointerId);if(!pointers.size){camera.drag=false;camera.pinch=0;if(!wasMoved)handleTap(e.clientX,e.clientY)}});
canvas.addEventListener('wheel',e=>{if(screen!=='world')return;e.preventDefault();camera.zoom=clamp(camera.zoom*Math.exp(-e.deltaY*.001),.38,1.45)},{passive:false});
canvas.addEventListener('pointerdown',e=>{if(screen!=='slingshot'||!slingshot)return;if(e.clientX<82&&e.clientY<82){exitLevel();return}const b=slingshot.current;if(b?.isStatic&&Math.hypot(e.clientX-b.position.x,e.clientY-b.position.y)<90){slingshot.dragging=true}else if(b&&!b.isStatic)activateSpecial()});
canvas.addEventListener('pointermove',e=>{if(screen!=='slingshot'||!slingshot?.dragging||!slingshot.current)return;const S=slingshot,dx=e.clientX-S.sling.x,dy=e.clientY-S.sling.y,d=Math.hypot(dx,dy),r=Math.min(115,d),x=S.sling.x+(d?dx/d*r:0),y=S.sling.y+(d?dy/d*r:0);Matter.Body.setPosition(S.current,{x,y})});
canvas.addEventListener('pointerup',e=>{if(screen==='slingshot'&&slingshot?.dragging)launchBird(slingshot.current.position.x,slingshot.current.position.y)});

$$('.tools button').forEach(b=>b.onclick=()=>{const t=b.dataset.tool;play('menu_select.mp3');if(t==='nest'){placement={type:'nest',pointerX:W/2,pointerY:H/2};$$('.tools button').forEach(x=>x.classList.toggle('active',x===b));toast('TAP THE MAP TO PLACE A NEST')}else if(t==='egg'){const nest=save.objects.find(x=>x.type==='nest'&&x.state==='empty');if(nest)openContext(nest);else toast('PLACE OR SELECT AN EMPTY NEST')}else if(t==='birds')showBirds();else if(t==='tasks')showTasks();else showLevels()});
$('#homeButton').onclick=()=>{screen='title';$('#hud').hidden=true;setMusic('title');play('menu_back.mp3')};$('#soundButton').onclick=()=>{soundOn=!soundOn;save.sound=soundOn;persist();if(!soundOn)Object.values(audio).forEach(a=>a.pause());else setMusic(screen==='world'?'ambient':'title');updateHud()};$('#zoomIn').onclick=()=>camera.zoom=clamp(camera.zoom*1.15,.38,1.45);$('#zoomOut').onclick=()=>camera.zoom=clamp(camera.zoom/1.15,.38,1.45);$('.close-context').onclick=()=>$('#contextMenu').hidden=true;$('#closePanel').onclick=closePanel;

function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;time+=dt;ctx.setTransform(DPR,0,0,DPR,0,0);if(screen==='title')renderTitle();else if(screen==='world')renderWorld();else if(screen==='slingshot'){updateSlingshot(dt);renderSlingshot()}requestAnimationFrame(frame)}
boot();
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
