g_achievements = {
	["Herr Helmet"] = { icon = "ACHIEVEMENT_FINISH_WORLD_1" },
	["Mr Moustache"] = { icon = "ACHIEVEMENT_FINISH_WORLD_2" },
	["Defeat of The King"] = { icon = "ACHIEVEMENT_FINISH_EPISODE" },
	["The Imposter"] = { icon = "ACHIEVEMENT_FINISH_WORLD_4" },
	["The Mysterious Escape"] = { icon = "ACHIEVEMENT_FINISH_EPISODE" },
	["Hovering Helmet"] = { icon = "ACHIEVEMENT_FINISH_WORLD_6" },
	["Mounting Moustache"] = { icon = "ACHIEVEMENT_FINISH_WORLD_7" },
	["Green Baron"] = { icon = "ACHIEVEMENT_FINISH_EPISODE" },
	["Hardhat Hidalgo"] = { icon = "ACHIEVEMENT_FINISH_WORLD_9" },
	["Mason Moustache"] = { icon = "ACHIEVEMENT_FINISH_WORLD_10" },
	["Episode 1 - Total Destruction"] = { icon = "ACHIEVEMENT_TOTAL_DESTRUCTION" },
	["Episode 1 - Score Addict"] = { icon = "ACHIEVEMENT_GET_XXX_POINTS" },
	["Episode 2 - Total Destruction"] = { icon = "ACHIEVEMENT_TOTAL_DESTRUCTION" },
	["Episode 2 - Score Addict"] = { icon = "ACHIEVEMENT_GET_XXX_POINTS" },
	["Episode 3 - Total Destruction"] = { icon = "ACHIEVEMENT_TOTAL_DESTRUCTION" },
	["Episode 3 - Score Addict"] = { icon = "ACHIEVEMENT_GET_XXX_POINTS" },
	["Episode 4 - Score Addict"] = { icon = "ACHIEVEMENT_GET_XXX_POINTS" },
	["Episode 4 - Total Destruction"] = { icon = "ACHIEVEMENT_TOTAL_DESTRUCTION" },
	["Episode 5 - Score Addict"] = { icon = "ACHIEVEMENT_GET_XXX_POINTS" },
	["Episode 5 - Total Destruction"] = { icon = "ACHIEVEMENT_TOTAL_DESTRUCTION" },
	["Episode 6 - Score Addict"] = { icon = "ACHIEVEMENT_GET_XXX_POINTS" },
	["Episode 6 - Total Destruction"] = {  icon = "ACHIEVEMENT_TOTAL_DESTRUCTION" },
	["Split it!"] = { icon = "ACHIEVEMENT_GET_BLUE_BIRD" },
	["Speed is the Essence"] = { icon = "ACHIEVEMENT_GET_YELLOW_BIRD" },
	["Boom Boom!"] = { icon = "ACHIEVEMENT_GET_BLACK_BIRD" },
	["Mother of all Bombs"] = { icon = "ACHIEVEMENT_GET_WHITE_BIRD" },
	["Return to Sender"] = { icon = "ACHIEVEMENT_GET_BOOMERANG_BIRD" },
	["Seeing Red"] = { icon = "ACHIEVEMENT_GET_BIG_BROTHER" },
	["Backward Compatibility"] = { icon = "ACHIEVEMENT_BACKWARD_SHOOTER", secret = true },
	["Space Invader"] = { icon = "ACHIEVEMENT_SPACE_INVADER", secret = true },
	["Woodpecker"] = { icon = "ACHIEVEMENT_SMASH_5000_WOOD_BLOCKS" },
	["Icepicker"] = { icon = "ACHIEVEMENT_SMASH_5000_ICE_BLOCKS" },
	["Stonecutter"] = { icon = "ACHIEVEMENT_SMASH_5000_ROCK_BLOCKS" },
	["Pig Popper"] = { icon = "ACHIEVEMENT_SMASH_5000_PIGS" },
	["Block Smasher"] = { icon = "ACHIEVEMENT_SMASH_50000_BLOCKS" },
	["Smash Maniac"] = { icon = "ACHIEVEMENT_SMASH_1000000_BLOCKS" },
	["Egg Hunter"] = { icon = "ACHIEVEMENT_EGG_HUNTER" },
	["Egg Cracker"] = { icon = "ACHIEVEMENT_EGG_CRACKER" },
	["Wilhelm Tell"] = { icon = "ACHIEVEMENT_WILHELM_TELL", secret = true },
	["Bull's Eye"] = { icon = "ACHIEVEMENT_BULLS_EYE" },
	["Angry Birds Fan"] = { icon = "ACHIEVEMENT_ANGRYBIRDS_FAN" },
	["True Angry Birds Fan"] = { icon = "ACHIEVEMENT_ANGRYBIRDS_TRUE_FAN" },
	["Angry Birds Addict"] = { icon = "ACHIEVEMENT_ANGRYBIRDS_ADDICT" },
	["Star Collector"] = { icon = "ACHIEVEMENT_STAR_COLLECTOR" },
	["Star Gatherer"] = { icon = "ACHIEVEMENT_STAR_GATHERER" },
	["Bird Slinger"] = { icon = "ACHIEVEMENT_BIRD_SLINGER" },
	["Royal Ringleader"] = { icon = "ACHIEVEMENT_FINISH_EPISODE" },
	["Billy The Pig"] = { icon = "ACHIEVEMENT_FINISH_WORLD_12" },
	["Clint Eastbacon"] = { icon = "ACHIEVEMENT_FINISH_WORLD_13" },
	["Aquiline Benefactor"] = { icon = "ACHIEVEMENT_UNLOCK_MIGHTY_EAGLE" },
	["Feather Picker"] = { icon = "ACHIEVEMENT_FEATHERS_1" },
	["Feather Collector"] = { icon = "ACHIEVEMENT_FEATHERS_2" },
	["Feather Gatherer"] = { icon = "ACHIEVEMENT_FEATHERS_3" },
	["Wild Pork Hickok"] = { icon = "ACHIEVEMENT_FINISH_WORLD_14" },
	["Cave Explorer"] = { icon = "ACHIEVEMENT_CAVE_EXPLORER" },
	["Cave Conquer"] = { icon = "ACHIEVEMENT_CAVE_CONQUER" },
	["King of the Caves"] = { icon = "ACHIEVEMENT_KING_OF_THE_CAVES" },
	["Ultimate Bejeweler"] = { icon = "ACHIEVEMENT_ULTIMATE_BEJEWELER"},
	["Hard as a Rock"] = { icon = "ACHIEVEMENT_HARD_AS_A_ROCK" },
	["Cakemonger"] = { icon = "ACHIEVEMENT_CAKEMONGER", secret = true },
}
filename="achievements.lua"
