-- TODO: could be numbers instead, useful like this for debugging. let's see.
-- TODO: comment each event that needs clarification
-- TODO: rearrange to groups


EID_GAME_INITIALIZED = "EID_GAME_INITIALIZED"

------- Golden egg events ----------
EID_GOLDEN_EGG_GAINED = "EID_GOLDEN_EGG_GAINED"
EID_GOLDEN_EGG_STAR_GAINED = "EID_GOLDEN_EGG_STAR_GAINED"
EID_MAIN_MENU_ENTERED = "EID_MAIN_MENU_ENTERED"
-------  Mighty eagle events ----------
EID_MIGHTYEAGLE_PURCHASED = "EID_MIGHTY_EAGLE_PURCHASED"
EID_MIGHTY_EAGLE_PURCHASE_CLOSE_CLICKED = "EID_MIGHTY_EAGLE_PURCHASE_CLOSE_CLICKED"
EID_MIGHTY_EAGLE_TRAILER_CLICKED = "EID_MIGHTY_EAGLE_TRAILER_CLICKED"
EID_MIGHTY_EAGLE_PURCHASE_CLICKED = "EID_MIGHTY_EAGLE_PURCHASE_CLICKED"
EID_MIGHTY_EAGLE_BUTTON_CLICKED = "EID_MIGHTY_EAGLE_BUTTON_CLICKED"
EID_NEW_EAGLE_HIGHSCORE = "EID_NEW_EAGLE_HIGHSCORE"
EID_EAGLE_FEATHER_GAINED = "EID_EAGLE_FEATHER_GAINED"
EID_ME_PURCHASE_CANCELLED_BY_USER = "EID_ME_PURCHASE_CANCELLED_BY_USER"
EID_ME_PURCHASE_FAILED_OTHER = "EID_ME_PURCHASE_FAILED_OTHER"
EID_MIGHTYEAGLE_RESTORED = "EID_MIGHTYEAGLE_RESTORED"
EID_CINEMATIC_TRAILER_CLICKED = "EID_CINEMATIC_TRAILER_CLICKED"

-- this message is sent when eagle is again available after locked time is depleted
EID_MIGHTY_EAGLE_AVAILABLE = "EID_MIGHTY_EAGLE_AVAILABLE"

--Mighty Eagle Unlock Once Events
EID_MIGHTYEAGLE_UNLOCK_ONCE = "EID_MIGHTY_UNLOCK_ONCE"
EID_MIGHTY_EAGLE_UNLOCK_ONCE_COOLDOWN = "EID_MIGHTY_EAGLE_UNLOCK_ONCE_COOLDOWN"
EID_FLURRY_EVENT_STARTED_BEFORE_COMPLETION = "EID_FLURRY_EVENT_STARTED_BEFORE_COMPLETION"

------------ TODO: sort these to groups
EID_GE_LEVEL_RESTARTED = "EID_GE_LEVEL_RESTARTED"
EID_GAME_RESUMED = "EID_GAME_RESUMED"
EID_GE_LEVEL_STARTED = "EID_GE_LEVEL_STARTED"
EID_LEVEL_STARTED = "EID_LEVEL_STARTED"
EID_LEVEL_RESTARTED = "EID_LEVEL_RESTARTED"
EID_TUTORIAL_WATCHED = "EID_TUTORIAL_WATCHED"
EID_WORLD_COMPLETED = "EID_WORLD_COMPLETED"
EID_BLOCKS_DESTROYED = "EID_BLOCKS_DESTROYED"
EID_BOOMERANG_BIRD_POPUP_SHOWN = "EID_BOOMERANG_BIRD_POPUP_SHOWN"
EID_BIRD_SHOT = "EID_BIRD_SHOT"
EID_SPACE_INVANDER = "EID_SPACE_INVANDER"
EID_BIRDS_COLLIDED_ON_FLY = "EID_BIRDS_COLLIDED_ON_FLY"
EID_ACHIEVEMENT_BULLSEYE = "EID_ACHIEVEMENT_BULLSEYE"
EID_CAKE_COLLECTED = "EID_CAKE_COLLECTED"
EID_LEVEL_COMPLETED = "EID_LEVEL_COMPLETED"
EID_GOLDEN_EGG_COMPLETED = "EID_GOLDEN_EGG_COMPLETED"
EID_LEVEL_FAILED = "EID_LEVEL_FAILED"
EID_GOLDEN_EGG_FAILED = "EID_GOLDEN_EGG_FAILED"
EID_LEVEL_COMPLETE_FIRST_TIME = "EID_LEVEL_COMPLETE_FIRST_TIME"
EID_GOTO_MAIN_MENU = "EID_GOTO_MAIN_MENU"
EID_GOTO_FACEBOOK_CONNECT = "EID_GOTO_FACEBOOK_CONNECT"
EID_FACEBOOK_LIKE_CLICKED = "EID_FACEBOOK_LIKE_CLICKED"
EID_EXIT_GAME = "EID_EXIT_GAME"
-- From android exit prompt
EID_EXIT_CONFIRMED = "EID_EXIT_CONFIRMED"
EID_GOTO_GAME = "EID_GOTO_GAME"
EID_HATCHERY_CLICKED = "EID_HATCHERY_CLICKED"
EID_CHANGE_LEVEL = "EID_CHANGE_LEVEL"
EID_GOLDEN_EGG_FROM_MENU = "EID_GOLDEN_EGG_FROM_MENU"
EID_BOOMERANG_BIRD_POPUP = "EID_BOOMERANG_BIRD_POPUP"
EID_STAR_POPUP = "EID_STAR_POPUP"
EID_REWARD_POPUP = "EID_REWARD_POPUP"
EID_LEVEL_ENDED = "EID_LEVEL_ENDED"
EID_LEVEL_PLAYED_WITH_EAGLE = "EID_LEVEL_PLAYED_WITH_EAGLE"
EID_NEW_HIGHSCORE = "EID_NEW_HIGHSCORE"
EID_THREE_STARS_GAINED = "EID_THREE_STARS_GAINED"
EID_STARS_GAINED = "EID_STARS_GAINED"
EID_EPISODE_THREE_STARRED = "EID_EPISODE_THREE_STARRED"
EID_LOAD_INTRO_CUTSCENE = "EID_LOAD_INTRO_CUTSCENE"
EID_LOAD_END_CUTSCENE = "EID_LOAD_END_CUTSCENE"
EID_PLAY_INTRO_CUTSCENE = "EID_PLAY_INTRO_CUTSCENE"
EID_PLAY_END_CUTSCENE = "EID_PLAY_END_CUTSCENE"
EID_EPISODE_COMPLETED = "EID_EPISODE_COMPLETED"
EID_END_CUTSCENE_FINISHED = "EID_END_CUTSCENE_FINISHED"
EID_SCROLL_TO_NEXT_WORLD = "EID_SCROLL_TO_NEXT_WORLD"
EID_GOTO_CREDITS = "EID_GOTO_CREDITS"
EID_DO_LOADING = "EID_DO_LOADING"
EID_PROCESS_FINISHED = "EID_PROCESS_FINISHED"
EID_EAGLE_BAIT_LAUNCHED = "EID_EAGLE_BAIT_LAUNCHED"
EID_SHOW_TUTORIAL = "EID_SHOW_TUTORIAL"
EID_CLOSE_TUTORIAL = "EID_TUTORIAL_CLOSED"
EID_SHOW_TUTORIALS = "EID_SHOW_TUTORIALS"
EID_LEAVE_GAME = "EID_LEAVE_GAME"

EID_ABOUT_MENU_OPENED = "EID_ABOUT_MENU_OPENED"
EID_LEVEL_RESTART_CLICKED = "EID_LEVEL_RESTART_CLICKED"
EID_ABID_CLICKED = "EID_ABID_CLICKED"
EID_LEVEL_GOALS_CLEARED = "EID_LEVEL_GOALS_CLEARED"
EID_LEVEL_COMPLETE_INIT = "EID_LEVEL_COMPLETE_INIT"



--- Challenge events ---
EID_CHALLENGE_STARTED = "EID_CHALLENGE_STARTED"
EID_CHALLENGE_STARTED_FIRSTTIME = "EID_CHALLENGE_STARTED_FIRSTTIME"
EID_CHALLENGE_RESTARTED = "EID_CHALLENGE_RESTARTED"
EID_CHALLENGE_LEVEL_ENDED = "EID_CHALLENGE_LEVEL_ENDED"
EID_START_NEXT_CHALLENGE_LEVEL = "EID_START_NEXT_CHALLENGE_LEVEL"
EID_NEW_CHALLENGE_AVAILABLE = "EID_NEW_CHALLENGE_AVAILABLE"
EID_CHALLENGE_FAILED = "EID_CHALLENGE_FAILED"
EID_CHALLENGE_COMPLETE = "EID_CHALLENGE_COMPLETE"
EID_CHALLENGE_COMPLETE_FIRST_TIME = "EID_CHALLENGE_COMPLETE_FIRST_TIME"
EID_CHALLENGE_MENU_ENTERED = "EID_CHALLENGE_MENU_ENTERED"
EID_CHALLENGE_UNLOCKED = "EID_CHALLENGE_UNLOCKED"
EID_ACHIEVEMENT_UNLOCKED = "EID_ACHIEVEMENT_UNLOCKED"
EID_ACHIEVEMENT_PROGRESS = "EID_ACHIEVEMENT_PROGRESS"
EID_PAUSE_CLICKED = "EID_PAUSE_CLICKED"
EID_GAME_PAUSED = "EID_GAME_PAUSED"
-- closed from pause menu resumed - button
EID_PAUSE_PAGE_CLOSED = "EID_PAUSE_PAGE_CLOSED"
EID_BACK_TO_GAME_CLICKED = "EID_BACK_TO_GAME_CLICKED"

----- Crystal events -----
EID_CRYSTAL_DEACTIVATED = "EID_CRYSTAL_DEACTIVATED"
EID_CRYSTAL_STARTED = "EID_CRYSTAL_STARTED"

---------------------- Link click events ----------------------
EID_GIFT_PURCHASE_CLICKED = "EID_GIFT_PURCHASE_CLICKED"
EID_AB_SHOP_CLICKED = "EID_AB_SHOP_CLICKED"
EID_LENOVO_ADFREE_CLICKED = "EID_LENOVO_ADFREE_CLICKED"
EID_NEWSLETTER_CLICKED = "EID_NEWSLETTER_CLICKED"
EID_SEASONS_CLICKED = "EID_GOTO_SEASONS"
EID_ABSHOP_LINK_CLICKED = "EID_ABSHOP_LINK_CLICKED"
EID_TWITTER_LINK_CLICKED = "EID_TWITTER_LINK_CLICKED"
EID_FACEBOOK_LINK_CLICKED = "EID_FACEBOOK_LINK_CLICKED"
EID_SEASONS_LINK_CLICKED = "EID_SEASONS_LINK_CLICKED"
EID_ROVIO_NEWS_SHOWN = "EID_ROVIO_NEWS_SHOWN"
-------------- Menu Manager Events ----------------
EID_PUSH_FRAME = "EID_PUSH_FRAME"
EID_POP_FRAME = "EID_POP_FRAME"
EID_CHANGE_SCENE = "EID_CHANGE_SCENE"
EID_SET_MENU = "EID_SET_MENU"
EID_MENUMANAGER_ROOT_CHANGED = "EID_MENUMANAGER_ROOT_CHANGED"
EID_FRAME_PUSHED = "EID_FRAME_PUSHED"
--------------
EID_GAMELUA_POPUP = "EID_GAMELUA_POPUP"
EID_REQUEST_LAYOUT = "EID_REQUEST_LAYOUT"
----------------
-- starts level loading sequence
EID_LEVEL_LOADING_INIT = "EID_LEVEL_LOADING_INIT"
-- 
EID_LEVEL_LOADING_DONE = "EID_LEVEL_LOADING_DONE"
-- draw loading page on top
EID_SHOW_LOADING_PAGE = "EID_SHOW_LOADING_PAGE"
-- hide loading page
EID_HIDE_LOADING_PAGE = "EID_HIDE_LOADING_PAGE"

--- ADS
EID_AD_READY = "EID_AD_READY"
EID_FULLSCREEN_AD_SHOWING = "EID_FULLSCREEN_AD_SHOWING"
EID_FULLSCREEN_AD_DISMISSED = "EID_FULLSCREEN_AD_DISMISSED"
filename="events.lua"
